////

jQuery Mobile Page Anatomy

Author: Max Lynch <maxlynch@uwalumni.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

1.1 What is the structure of a jQuery Mobile page?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
You need to set up a jQuery Mobile page with a page header, a page content area and page footer.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Pages are the fundamental building blocks of a jQuery Mobile application. jQuery Mobile offers a convenient structure that can be used to quickly build pages, though it does not require a specific structure.

In jQuery Mobile, pages are placed inside of the <body> element of the main document. You can include different components by using the data-role attribute. The data-role attributes are HTML5 attributes used by the jQuery Mobile framework to determine how to transform the markup into a enhanced styled widget.

Here's the code to create a simple page with a basic header, content area and footer:

.A Simple jQuery Mobile Page
[source,html]
----
<!DOCTYPE html> 
<html> 
<head> 
	<title>My Page</title> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="/css/jquery.mobile.min.css">
	<script src="/js/jquery.min.js"></script>
	<script src="/js/jquery.mobile.min.js"></script>
</head> 
<body>
	<div data-role="page">
		<div data-role="header">
			<h3>Title</h3>
		</div>
		<div data-role="content">
			Page content goes here
		</div>
		<div data-role="footer">
			<h3>Footer</h3>
		</div>
	</div>
</body>
----


Discussion
++++++++++++++++++++++++++++++++++++++++++++

In the example page, you have a header, content area and footer, which are standard jQuery Mobile components that make up a page. As mentioned, you can put anything you like inside of a page, though the standard header, content and footer sections have many nice built-in features that make it easier to incorporate common mobile features such as navigation bars or back buttons.

The content area can contain any standard HTML elements.  You can style these elements with custom styles in another stylesheet immediately after the jQuery Mobile stylesheet. 

