////

Author: Adam Bradley <adambradley25@gmail.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////


1.11 Navbar Icons
~~~~~~~~~~~~~~~~~

Problem
+++++++
You want to add icons to your Navbar. 

Solution
++++++++
Like with any application, or even your car's dashboard, icons help users quickly identify an expected outcome when an interaction occurs. By default, jQuery Mobile comes with a basic set of icons that can be easily displayed within various elements, including Navbars. After jQuery Mobile performs its progressive enhancement magic, the assigned icons help to provide users with a familiar "app-like" appearance. Along with choosing which icon to display for each Navbar link, you can also customize an icon's position relative to each nav link's text.

.Navbar with Icons
[source,html]
----
<div data-role="footer">		
	<div data-role="navbar">
		<ul>
			<li><a href="#" data-icon="home">Home</a></li>
			<li><a href="#" data-icon="info">Info</a></li>
			<li><a href="#" data-icon="search">Search</a></li>
		</ul>
	</div><!-- /navbar -->
</div><!-- /footer -->
----

Discussion
++++++++++
Out of the box, jQuery Mobile provides a standard set of icons commonly used, such as "home", "info" or "search" icons. __See ########## for more information on jQuery Mobile icons.__ By using the 'data-icon' attribute, you can assign icons to individual. By default, they will be positioned on top of their link's text, which is also customizable.

By using the 'data-iconpos' attribute within the Navbar container, you are able to override the default _top_ icon positioning. Vaild 'data-iconpos' values include: __left, right, top, bottom__.

.Navbar with Bottom Positioned Icons
[source,html]
----
<div data-role="navbar" data-iconpos="bottom">
----

Notice in the provided example the 'data-iconpos="bottom"' is not assigned to an individual link but instead to the  Navbar container.

