////

I MOVED THIS TO CHAPTER 2 RECIPE 7 BECAUSE IT WAS THE FIRST CHAPTER TO MENTION TOOLBARS.
jQueryMobile supports three types of toolbars.
1.Header bars which is displayed as the top most item before page content.
Normally used to show page title and buttons/icons.
2.Footer bars which is displayed as the bottom most item after page content.
Normally contains buttons/icons.
3.Navbars which can be displayed within header/footer bars or with in page content to show seperate level of buttons/icons/other controls. 

Author: John Chacko <poonkave@gmail.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

1.8 Embedding Controls in Toolbars
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
You want to embed controls in the header or footer toolbars on the page. For example, you want to let the user toggle the current language of the page.


Solution
++++++++++++++++++++++++++++++++++++++++++++
To do this, you need to be able to place a control into the header and position it properly to the right or left side.

[source, html]
---- 
<!DOCTYPE html>
<html>
  <head>
    <title>Embedding controls in toolbar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/jquery.mobile.min.css">
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.mobile.min.js"></script>
	<style>
		#home-header .ui-select { 
			float: right
		}
	</style>
  </head>
  <body>
    <div id="home" data-role="page" data-theme="b">
		<div id="home-header" data-role="header" data-position="inline">
			<select name="language" id="language" data-native-menu="false" data-theme="b">
				<option value="English">English</option>
				<option value="French">French</option>
				<option value="Russian">Russian</option>
				<option value="Polish">Polish</option>
			</select>
			<h1>Home Page</h1> 

		</div>
		<div data-role="content"></div> 
    </div>
  </body>
</html>
 
Discussion
++++++++++++++++++++++++++++++++++++++++++++
In order to fit the control the right of the header, you've set it to float right. 
