////

Author: Cory Gackenheimer <cory.gack@gmail.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

7.6 Touch vs. Click
~~~~~~~~~~~~~~~~~~~

Problem
+++++++
You want to add great touch interaction to your jQuery Mobile application but managing bindings to touch and click events is problematic. Some mobile browsers are enhanced for touch support by adding touch events. On touch supported browsers these events are also followed by a click event - after a 300 millisecond delay - which can present interesting opportunities when developing mobile applications.

Solution
++++++++
jQuery Mobile has abstracted touch and click functionality to combat some of the issues that are problematic within the touch interfaces. These are presented in the form of virtual mouse events. As a developer you can utilize these virtual mouse events to register events and let jQuery Mobile handle the registering the correct mouse or touch event in order to produce the most efficient response possible.

Discussion
++++++++++
The virtual mouse events are registered within your jQuery Mobile application in the same manner as any other event, choose them to normalize your event handling between the touch and mouse events you wish to capture.

Virtual Mouse Events::
[horizontal]
	vmouseover;;
		normalizes touch and mouseover events
	vmouseout;;
		normalizes touch and mouseout events
	vmousedown;;
		normalizes touchstart and mousedown events
	vmousemove;;
		normalizes the touchmove and mousemove events
	vmouseup;;
		normalizes the touchend and mouseup events
	vclick;;
		normalizes touchend and mouseup events
		note::: Since on touch devices the click event is triggered 300 milliseconds after the initial tap, the vclick event is triggered after vmouseup.  If your application is designed to move or alter content on initial tap, the target of the subsequent click event that is triggered will possibly be different than the target of the originating tap. If you plan to manipulate content on touch, it is recommended to utilize the click event instead of the vclick event.
	vmousecancel;;
		normalizes touch and mousecancel events


Here is an example of how you could register the vmouseover handler, the other events can be registered similarly with the above event targets.
----
$( "#vmousetarget" ).on( "vmouseover", function( event ) {
	//normalized event handler
});
----
