////

Author: Tyson Cadenhead <tcadenhead@appendto.com> Nov. 27, 2012
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

7.7 Creating an image gallery with the swipe event
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
If you want to create a photo gallery on a mobile device, there isn't a jQuery plugin for this.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Fortunately, you can use jQuery Mobile's events to build your own. The swipe event works well for this. 

Discussion
++++++++++++++++++++++++++++++++++++++++++++
To implement an image gallery, we will need to use a combination of HTML, CSS and JavaScript. The HTML will just be a div with our images inside of it.

----
include::recipe-8-code/gallery.html[]
----

With our CSS, we will hide all of the images that are not active.

----
include::recipe-8-code/gallery.css[]
----

The JavaScript is where most of the magic will happen. JQuery Mobile has some really good transitions built into it, so we can just extend them and look for the “data-transition” attribute on the gallery div to determine what our transition should be. We've got it set to "flow" right now, but it can just as easily be set to "slide" or "fade" or any of the other transition we want.

----
include::recipe-8-code/gallery.js[]
----

Now, when we swipe left, the next image will be shown. When we swipe right, the previous image will be be shown. Even though there isn't a plugin to create an image gallery out of the box, you can easily make one with very minimal code.