////

Author: Mattias Kihlstrom <mattias@kihlstrom.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

6.8 Options for Displaying Elements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Problem
+++++++
When designing a form you often want to group elements together. This could be as simple as putting a label just before its input element and wrapping a fieldset around them. But how would you go about if you for instance have three radio buttons grouped together horizontally and you also want them to fill up the full width of the screen?

Solution
++++++++
Radio buttons can be grouped together by putting them inside a fieldset with data-role="controlgroup". Adding data-type="horizontal" makes sure they are side by side instead of below each other (as long as the browser supports display: inline-block;). But if you want them to use 100% of the width you will have to add some extra styling, specific to the number of radio buttons in the group.

Discussion
++++++++++
In the following example there are three radio buttons that we want to group horizontally and also to take upp the full width of its container. The surrounding fieldset is specified as a horiontal control group. In order to style everything we add two classes. One general for all full width groups and one specific to the number of radio buttons in this group. The following HTML snippet is meant to be part of a jQuery Mobile page.

[source, html]
----
<fieldset data-role="controlgroup" data-type="horizontal" class="fullwidth items-3">
  <input type="radio" name="payment-method" id="payment-method-1" value="credit" checked="checked">
  <label for="payment-method-1">Credit</label>
  <input type="radio" name="payment-method" id="payment-method-2" value="debit">
  <label for="payment-method-2">Debit</label>
  <input type="radio" name="payment-method" id="payment-method-3" value="cash">
  <label for="payment-method-3">Cash</label>
</fieldset>
----

In the CSS we set the width of each ui-radio div that jQuery Mobile creates. This width in percent must match the number of items in the group (in this case 100% / 3). Then we make each label use up all of that width. And since we don't want to waste any pixels we will also reset some margins.

[source, css]
----
.fullwidth.items-2 .ui-radio { width: 50%; }
.fullwidth.items-3 .ui-radio { width: 33.3333333%; }
.fullwidth.items-4 .ui-radio { width: 25%; }
.fullwidth.items-5 .ui-radio { width: 20%; }
.fullwidth .ui-radio { margin-right: 0; }
.fullwidth .ui-radio label { margin-left: 0; width: 100%; }
----

It is not only radio buttons that can be grouped in this manner. Here is a modified set of CSS rules that makes this work for select boxes as well.

[source, css]
----
.fullwidth.items-2 .ui-radio, .fullwidth.items-2 .ui-select { width: 50%; }
.fullwidth.items-3 .ui-radio, .fullwidth.items-3 .ui-select { width: 33.3333333%; }
.fullwidth.items-4 .ui-radio, .fullwidth.items-4 .ui-select { width: 25%; }
.fullwidth.items-5 .ui-radio, .fullwidth.items-5 .ui-select { width: 20%; }
.fullwidth .ui-radio label, .fullwidth .ui-select .ui-btn { width: 100%; }
.fullwidth .ui-radio, .fullwidth .ui-radio label { margin: 0; }
.fullwidth .ui-select { margin: 0 -2px; }
.fullwidth .ui-select:first-child { margin-left: 0; }
----
