////

Author: Anu Shahi <anu.shahi@gmail.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

7.8 Form Validation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
+++++++++++++++++++++++++++++

Enabling client-side form validation for a typical jQuery Mobile application presents a range of challenges. Firstly, the single page application approach requires validation rules to be applied during initialization of a specific form page. Secondly, due to the markup generated by jQuery Mobile during progressive enhancement, error messages must be placed appropriately around elements that fail validation, such as select lists and radio controls. This ensures errors blend in sensibly when viewed within enhanced forms. Finally, event handlers must be registered to trigger as you type validation for heavily enhanced form elements, where binding click handlers to the original native controls has no effect, such as select lists and radio controls.

Solution
+++++++++++++++++++++++++++++
Create a simple validation module that configures the jQuery validation framework (see http://docs.jquery.com/Plugins/Validation) to insert error labels sensibly around enhanced elements, together with binding additional event handlers to trigger validation of heavily enhanced elements. The jQuery validation framework allows validation rules to be specified and easily bound to target form elements in both a declarative and programmatic way. Validation is performed elegantly by triggering validation of form elements after an initial form submission, after which as you type validation is enabled for each control.

The following snippet of code describes the general approach for discussion. In this case, validation will be enabled for +myform+, meaning the form will not be submitted until inputs +firstElement+ and +anotherElement+ contain non-empty values.

----
// enable validation for myform
var form = $( "#myform" );
formValidation.validate( form, {
  rules: {
    firstElement: "required",
    anotherElement: "required",
  }
});
----

Discussion
+++++++++++++++++++++++++++++

Let's start with a sample form page used to capture feedback on people's favourite snacks. The form includes standard jQuery Mobile constructs representing a select list, radio button and a simple text area:

----
<div data-role="page" id="feedback">
  <div data-role="header">
    <h1>Feedback Form</h1>
  </div>
  <div data-role="content">
    <form action="/snackreview" method="POST">
      <div data-role="fieldcontain">
        <label for="region">Please enter your region:</label>
        <select name="region" id="region" data-native-menu="false">
          <option></option>
          <option>North</option>
          <option>South</option>
          <option>East</option>
          <option>West</option>
        </select>
      </div>
      <div data-role="fieldcontain">
        <fieldset data-role="controlgroup">
          <legend>
            Please select your favourite snack:
          </legend>
          <input type="radio" name="snack" id="cheetos">
          <label for="cheetos">Cheetos</label>
          <input type="radio" name="snack" id="doritos">
          <label for="doritos">Doritos</label>
          <input type="radio" name="snack" id="fritos">
          <label for="fritos">Fritos</label>
          <input type="radio" name="snack" id="sunchips">
          <label for="sunchips">Sun Chips</label>
        </fieldset>
      </div>
      <div data-role="fieldcontain">
        <label for="feedback">Please describe why you love your favourite snack:</label>
        <textarea name="feedback" id="feedback"></textarea>
      </div>
      <div data-role="fieldcontain">
        <button type="submit" data-theme="a">Send</button>
        <a href="#home" data-role="button">Cancel</a>
      </div>
    </form>
  </div>
</div>
----

The validation requirement for our sample form is that all fields are mandatory. To enable such validation on our target page, we bind a function to the +pageinit+ event. This function selects the form and invokes the form validation module with the target form and a simple object containing form specific validation rules:

----
$( document ).on( "pageinit", "#feedback", function( event ) {
  var form = $( event.target ).find( "form" );
  formValidation.validate( form, {
    rules: {
      region: "required",
      snack: "required",
      feedback: "required"
    }
  });
});
----

Many types of validation are supported by the jQuery validation framework. Validation rules may be added declaratively with support provided for the new set of HTML5 input types. Multiple rules may be combined for an element as follows:

----
rules: {
  measure: {
    required: true,
    digits: true,
    maxlength: 6
  }
}
----

As already outlined, validation of our sample form is enabled by invoking the +formValidation+ module, which configures the jQuery validation plugin as follows:

----
var formValidation = (function( $ ) {

  var settingsForMobile = {
    errorPlacement: function( error, element ) {
      var container;
      if ( element.is( ":radio, select" ) ) {
        container = element.closest( "[data-role='fieldcontain']" );
        if ( container.length ) {
          error.appendTo( container );
        }
      }
      else {
        error.insertAfter( element );
      }
    }

  };

  function handleChangeEvent( event ) {
    // code based on the jQuery validation framework
    var validator = $.data( this[0].form, "validator" );
    validator.element( this[0] );
  };

  return {
    validate: function( form, rules ) {
      var validator,
        validationModel = $.extend( true, {}, settingsForMobile, rules ),
        changeEventTargets = "[type='radio'], [type='checkbox'], select, option";

      validator = form.validate( validationModel );
      form.validateDelegate( changeEventTargets, "change", handleChangeEvent );
    }
  };

})( jQuery );
----

The module exposes a single method called +validate+, which performs the validator setup. Firstly, a +validationModel+ object is created by merging the form specific validation rules with a +settingsForMobile+ object. The +settingsForMobile+ object contains an error placement function specific to jQuery Mobile. This function is invoked by the jQuery validation framework to place error labels for invalid elements; in this case, the function places errors for radio controls and select lists by searching for the closest element that is a jQuery Mobile field container. It then appends the error label to the container, therefore presenting error messages cleanly below radio control groups and select lists. All other controls, such as input text fields and text areas have their error labels inserted directly below. Using this approach, a number of error placement strategies may be created appropriate to the application.

After declaring the required variables, the +validate+ method, provided by the jQuery validation plugin, is invoked on the form instance. This initialises the validator with the given validation model options; validation is now enabled for the provided form and will be triggered on initial form submission.

The final line in the +validate+ method invokes the +validateDelegate+ function provided by the jQuery validation plugin. This call attaches the +handleChangeEvent+ function to the change events of all select and radio button controls within the provided form. Using this approach, we can detect changes made to enhanced radio/select controls and trigger validation by invoking the +handleChangeEvent+ function, therefore providing as you type validation for such controls. It is important to note that simple elements, such as input text fields and text areas work correctly out of the box, due to their mark-up being minimally enhanced.

Error labels for invalid elements may be styled easily as follows:

----
label.error {
  display: block;
  color: #fe7c6d;
  margin-top: 0.4em;
}
@media all and ( min-width: 450px ) {
  label.error { margin-left: 22.5%; }
}
----

As shown, error labels are given a class attribute named +error+, allowing custom styling to be applied easily. In this case, the error label is displayed as a block element with an appropriate text color and top margin; for screen widths greater than 450px, a media query is applied to add a larger left margin. This allows an error label to appear immediately under the control, rather than under its field label. Overall, with a little configuration, validation of forms enhanced by jQuery Mobile is a straightforward process with plenty of options for customization.

