////

Author: Tyson Cadenhead <tcadenhead@appendto.com> 11/29/2012

////

11.7 Offline storage alternatives
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
What different types of offline storage do we have access to?

Solution
++++++++++++++++++++++++++++++++++++++++++++
There are many ways to store data offline. Using the client-side to store large amounts of data was largely ignored by most browsers until recently, so support for different types of storage varies.

Discussion
++++++++++++++++++++++++++++++++++++++++++++
Offline storage comes in many shapes and sizes. These include:

* session
* cookies
* localStorage
* web SQL
* indexedDB

JavaScript maintains a session as long as the client doesn't refresh the page, so you can actually use the session to maintain storage in single-page applications using a basic getter / setter pattern. One benefit of using the session is that it will work in every browser that supports JavaScript. The downside is that as soon as the page is refreshed, everything is lost.

----
var Session = function () {

    // This is where we will store the data
    this.data = {};

    // When we call this method, we will return the data that matches the name
    this.get = function (name) {
        return this.data[name];
    };

    // This method will set the data based on the name / value pair that is passed in    
    this.set = function (name, value) {
        this.data[name] = value;
    }

};

var session = new Session();

// Set the name
session.set("name", "John Doe");

// Get the name
console.log(
	session.get("name")
); // Returns "John Doe"
----

Cookies are maintained when the page is reloaded, but they have size limitations. Most browsers also allow their users to turn cookies off. Historically, cookies have mostly been used to keep small pieces of information on the client-side such as a name, an authorization code or an email address.

----
var Cookie = function () {

    // When we call this method, we will return the data that matches the name
    this.get = function (name) {
    
        // The cookies are stored as a big string, we'll need to split them into an array
        var cookies = document.cookie.split(";");
        
        // Loop over all of the cookies
        for (var i = 0; i < cookies.length; i++) {
        
            // Seperate the name and value pairs
            cookies[i] = cookies[i].split("=");
            
            // If the name passed in matches the name of the cookie, return it
            if (cookies[i][0] === name) {
                return unescape(cookies[i][1]);
            }
            
        }
    
    };
    
    // This method will set the data based on the name / value pair that is passed in 
    this.set = function (name, value, numberOfDays) {
        
        // Create a new date for the expiration
        var expiration = new Date();
        
        // Set the expiration date to the number of days passed in
        expiration.setDate(expiration.getDate() + numberOfDays);
        
        // Add the expration date to the value
        value = escape(value) + "; expires=" + expiration.toUTCString();
        
        // Set the cookie
        document.cookie = name + "=" + value;
        
    };

};

var cookie = new Cookie();

// Set the name
cookie.set("name", "John Doe");

// Get the name
console.log(
	cookie.get("name")
); // Returns "John Doe"
----

Local Storage using name / value pairs can be a really good option for persisting data on the client-side. Local storage is supported by virtually every modern browser from Internet Explorer 8 and up.

----
// Check to see if the browser supports local storage
if (typeof localStorage) {

    // Set the data
    localStorage["name"] = "John Doe";
    
    // Get the data
    console.log(
        localStorage["name"]
    );
    
}
----

Web SQL is significantly more robust than any of the other options. With Web SQL, you can write SQL statements directly in your JavaScript. Web SQL enjoys support in all modern webkit browsers. If your application is exclusively targeted for mobile devices, Web SQL may be the right fit. Unfortunately, Firefox and Internet Explorer don't support Web SQL yet.

----
// Create a new database
var db = openDatabase(
	'users',											// The name of the database
	'1.0', 												// The database version
	'A database for the users of the application', 		// A description of the database
	2 * 1024 * 1024 									// The estimated size of the database
);

// Every database transaction is performed inside of the transaction method
db.transaction(function (transaction) {

	// Create a table called "people"
	transaction.executeSql('CREATE TABLE IF NOT EXISTS people (id unique, name)');

	// Insert a person into the database
	transaction.executeSql('INSERT INTO people (id, name) VALUES (1, "John Doe")');

});

// Start a new transaction to select the person
db.transaction(function (transaction) {

	// Select all the people
	transaction.executeSql('SELECT * FROM people', [], function (transaction, results) {
		
		// Loop over all of the rows in the response
		for (var i = 0; i < results.rows.length; i++) {

			// Get the person
			var result = results.rows.item(i);

			// Log the person's name
			console.log(result.name);

		}
	});
});
----

IndexedDB is designed for storing large amounts of data. It performs really well when searching data that uses indexes. IndexedDB is partially supported by Firefox, Chrome and Internet Explorer 10, but not Safari.

IndexedDB is still in its infancy, so the implementation varies from one browsers to the next. According to W3C, IndexedDB was designed to be used with a library wrapper since working with it tends to be overly complex. One of the best examples of a IndexedDB wrapper is Lawnchair ( http://brian.io/lawnchair ).

----
// Create a store
var store = new Lawnchair({
    name: 'user'
}, function(user) {

    // Set the name and ID of John Doe
    var john = {
        key: '1',
        name: 'John Doe'
    };

    // Save him
    user.save(john);

    // Get John
    user.get('1', function(person) {
        console.log(person);
    });
});
----

The above example will only use indexedDB if your browser supports it. Otherwise it will fall back on a different storage type.

As you can see, there is no shortage of storage types. Each has it's own advantages and disadvantages and they should all be carefully weighed when choosing the one that will work best for your application.