////

Author: Tyson Cadenhead <tcadenhead@appendto.com> Nov. 26, 2012
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

4.4 Executing links as AJAX calls 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Native apps rarely have static transitions from one page to another. In that spirit, we would like to retrieve our pages with Ajax and render them using transitions. We would also like to use progressive enhancement to make the links work in browsers that have JavaScript turned off.

Solution
++++++++++++++++++++++++++++++++++++++++++++

With jQuery Mobile, any links in the same domain are automatically retrieved with Ajax as long as they contain a div with a data-role="page" property. When the page is transitioned to, the url in the address bar will automatically update to display the requested link.

Discussion
++++++++++++++++++++++++++++++++++++++++++++

To demonstrate how links should be set up, we need two separate pages. The homepage below links to the subpage. Note that it is just using a standard link. Also note that all of the content is wrapped with a div with a data-role of page. The data-role tells jQuery Mobile that everything inside of it is the content of the page. Everything outside of the page will be thrown out in the case of an ajax call.

----
<!-- homepage.html -->
<div data-role="page" id="homepage">
    <h1>Homepage</h1>
    <a href="subpage.html" data-transition="turn">Subpage</a>
</div>
----

Next, we need to create the subpage. It will link back to the homepage so that you can click back and forth infinitely.

----
<!-- subpage.html -->
<div data-role="page" id="subpage">
    <h1>Subpage</h1>
    <a href="homepage.html" data-transition="turn">Homepage</a>
</div>
----

The only thing to note about the link itself is that you can specify any valid jQuery mobile transition via the data-transition property.

Building our links and pages this way will achieve our goal of using progressive enhancement and closely replicating the transitions found in native apps. Rendering the html like we're building a normal link tag will also add to your SEO value. 