////

Author: John Chacko <johns221b@gmail.com>
Chapter Leader approved: <date>
Copy edited: Ralph Whitbeck <rwhitbeck@appendto.com> Nov 23, 2012
Tech edited: <date>

////

1.2 What is jQuery?
~~~~~~~~~~~~~~~~~~~
By _John Chacko_

JavaScript is a scripting language that adds behaviors and interactions to the web.  JavaScript has been around since 1995 but it was the introduction of Ajax (Asynchronous JavaScript and XML) which was nothing more the interrelated technologies used together to make asynchronous web applications, since then JavaScript's popularity has exploded.  Google made this technique mainstream by making it's GMail web application asynchronous.

JavaScript however isn't perfect and each browser vendor has a different interpretation on how to implement the specification (ECMAScript).  Because of these differences JavaScript can work just fine in one browser but completely differently in another.  Web developers found themselves writing tons of code to handle all these cross-browser "quirks". 

In January 2006 at a Barcamp in NYC, John Resig showed off three things.  One of those was jQuery, a JavaScript library that abstracts away cross-browser "quirks" and allows the developer to not have to think about it.  They essentially can "Write less, do more." which is the jQuery tag line.  jQuery is free, open source software that is licensed under the MIT license (http://jquery.org/license/).

Today, jQuery is the most popular JavaScript library in use. jQuery is used on over 59.2% of the top 10,000 sites as tracked by Built With Trends as of November 2012.  That number continues to climb at a steady rate.  You can see the latest percentages at http://trends.builtwith.com/javascript/jQuery.

jQuery allows JavaScript developers to take native code like this:

[source,javascript]
----
  // Grab a NodeList
  var kittens  = document.querySelectorAll(".kitten");

  // Show images 'fast'
  show(kittens, "fast");

  // Function responsible for showing
  function show (list, speed) {
      
      // Setup variables to use internally
      var index, opacity, interval, timing;
      var velocity = {"fast": 20, "slow": 60};
      
      // Determine if speed is a number, or a string
      timing = ~toString.call(speed).indexOf("Number")
          ? speed * .01
          : velocity[speed] || 40;
      
      // Convert elements into array
      if (list.nodeType && list.nodeType === 1) {
          list = [list];
      }
      
      // Set all items in collection to transparent
      for (index = 0; index < list.length; index++) {
          list[index].style.opacity = 0;
      }
      
      // Set opacity-increasing interval
      interval = setInterval(function () {
          for (index = 0; index < list.length; index++) {
              opacity = parseFloat(list[index].style.opacity);
              list[index].style.opacity = opacity + .01;
          }
          // If images are fully opaque, clear interval
          if (opacity >= 1) {
              clearInterval(interval);
          }
      }, timing);
      
  }
----

and write one line of code like this:

[source,javascript]
----
  $(".kitten").show("fast");
----

Above line of jQuery can be broken down into three parts.

First you need to declare and call the jQuery object.  We do that by calling it's alias '$'.

Next we select the element whose id is 'mybutton'.  The jQuery object will take any selectors that conform to the CSS 1-3 specs plus some pseudo selectors that are apart of jQuery. In our example about we will select a button whose id is 'mybutton' on a page.

The combined jQuery object and selector returns a jQuery Collection that can then have worked performed on.  jQuery has a rich API that allows you to do something on the returned collection.  In our example we are attaching a listener to the 'click' event where redirect' is the name of the listener function.

Some broad actions you can perform using jQuery are things like selecting and manipulating DOM elements, DOM traversal, creating animations, handling events, and developing Ajax applications, easily.

You can find out more about the jQuery API at http://api.jquery.com.  This book assumes you have a good understanding of how jQuery works.