////

Notes
-----

* Discuss various approaches for using the mobileinit method for configuring defaults.
* Discuss some important default settings which can be configured, like namespace, default transitions, etc.
* List out the other default settings which can be modified.

Author: Kinshuk Kar <kinshuk.kar@gmail.com>

////

#.# Recipe Title
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using mobileinit to configure jQuery Mobile defaults.


Problem
++++++++++++++++++++++++++++++++++++++++++++
jQuery Mobile has a number of default settings which it uses for its markup enhancements and other functionality. In most cases the default settings suffice but there maybe situations where one would need to modify the default settings.

Solution
++++++++++++++++++++++++++++++++++++++++++++
jQuery Mobile triggers an event named "mobileinit" on the document object just when it begins execution. This event can be used as a handle to configure the defaults before jQuery Mobile goes ahead and uses them.

The following example shows how the mobileinit event can be handled to configure jQuery Mobile's defaults - 

----
include::recipe-1-code/mobileinit.html[]
----

[CAUTION]
===============================
The "mobileinit" handler should be placed just before the jQuery Mobile inclusion, as the handler would not be registered when the event fires.
===============================


Discussion
++++++++++++++++++++++++++++++++++++++++++++
We can also achieve the achieve the same effect as above by extending the $.mobile object using jQuery. Following is the snippet for it - 

[source,javascript]
---
$( document ).bind( "mobileinit" , function() {
  $.extend(  $.mobile , {
    foo : bar
  });
});
---

<<XREF_TABLE>> shows the options that can be configured through the $.mobile object.

[[XREF_TABLE]]
.Configurable options available
[options="header"]
|=======
|Property|Version added|Default value|Description
|autoInitializePage|1.0|"true"|Whether to automatically call the $.mobile.initializePage when the page is ready. If set to false, $.mobile.initializePage has to be manually called else the page will be hidden.
|gradeA|1.0|a function returning the value of $.support.mediaquery or if browser is IE7+|function which will check the basic support conditions.
|defaultPageTransition|1.0|"fade", "slide" in 1.0|The default transition to be used for page transitions.
|defaultDialogTransition|1.0|"pop"|The default transition to be used for dialog changes.
|activePageClass|1.0|"ui-page-active"|The CSS class assigned to the page in view and during transitions.
|activeBtnClass|1.0|"ui-btn-active"|The CSS class assigned for buttons in the "active" state.
|focusClass|1.1|"ui-focus"|The CSS class assigned for "focus" form element state.
|loadingMessage|1.0|"loading"|The text that appears when a page is loading. Set it to false to disabling the loading message.
|loadingMessageTextVisible|1.1|"false"|Sets whether the text should be displayed in a loading message box. Note:- Page load error message will always be visible.
|loadingMessageTheme|1.1|"a"|The theme to be used for the loading message box when the text is visible.
|pageLoadErrorMessage|1.0|"Error Loading Page"|Sets the text that appears when a page fails to load.
|pageLoadErrorMessageTheme|1.1|"e"|The theme to be used by the error message box.
|minScrollBack|1.0|250|The minimum scroll distance to be remembered when a user returns to a page.
|=======

