////

Recipe for getting started with jQuery Mobile and Google Maps

Author: Anne-Gaelle Colom <coloma@wmin.ac.uk>

TODO: need to add screen shots, and should I add full screen code as well in the discussion?

////

10.10 Getting Started with jQuery Mobile and Google Maps
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
You want to incorporate a Google map in your jQuery Mobile application. 

Solution
++++++++++++++++++++++++++++++++++++++++++++
You need to merge the jQuery Mobile elements and your existing map together, making sure this does not lead to any conflict of naming. You also need to ensure that the scripts and style elements are loaded in the correct order:

[source,html]
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>Google Maps JavaScript API v3 Example: Map Simple</title>
    <link rel="stylesheet"  href="http://code.jquery.com/mobile/latest/jquery.mobile.css" />
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/latest/jquery.mobile.min.js"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
      function initialize() {
        var myLatlng = new google.maps.LatLng(-34.397, 150.644);
        var myOptions = {
          zoom: 8,
          center: myLatlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
      }
    </script>
    <style type="text/css">
      #map_canvas { height: 560px; width: 100%  }
    </style>
  </head>

  <body onload="initialize()">

    <div data-role="page">
      <div data-role="header" data-position="fixed">
        <h1>My Google Map in jQuery Mobile</h1>
      </div><!-- /header -->

      <div data-role="content">
        <div id="map_canvas" ></div>
      </div><!-- /content -->

      <div data-role="footer" data-position="fixed">
        <h4>Map Example 1</h4>
      </div><!-- /header -->
    </div><!-- /page -->

  </body>
</html>

Discussion
++++++++++++++++++++++++++++++++++++++++++++
The best way here is often to start with your Google Map page and add the jQuery Mobile elements around the page. The map container (<div id=”map_canvas”> </div> in the example above) will be part of the jQuery Mobile content container. The scripts relating to the map will be placed after the jQuery Mobile scripts and css. Your custom css, to define the map container should appear after the jQuery Mobile css. The first script will load the Google map api, and the second one is to create and initialize your map object. The body tag will contain the function that will initialize the Google map. From there, you can build further by, for example, adding further elements and services, such as geocoding, directions, etc.

You may encounter a difficulty if you try to set the map container’s height to 100%, if you want the map to appear full screen. This is due to the fact that if you set the map container to 100%, it will be relative to its parent container. That means that to set the map container to 100%, you also need to set the height of the content div, the page, body and html to the same value or an error will be thrown and the map will not display. You may also want to add a padding of 0 pixel to all those elements. 

(SHOULD I ADD THE FULL CODE FOR FULL SCREEN VERSION HERE?)