////

Author: Ryan Westphal <ryan@trippingthebits.com>

////

10.8 Uploading Photos on iOS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Users cannot upload files in Mobile Safari. When you put:

----
<input type="file" name="photo" />
----

into your web page, Mobile Safari shows the user a Choose File button but it is disabled. You cannot enable it with HTML, CSS, or JavaScript.


Solution
++++++++++++++++++++++++++++++++++++++++++++
First, in your HTML form where you have just a file input, add a div for iOS. This solution requires users to install a third-party utility, Picup, from the Apple App Store. Your HTML for iOS should make that clear and provide a link to install Picup. You will also need a Browse button, which launches Picup via iOS URL scheme handling, and a hidden input to store a URL Picup returns to your app.

When the user taps the Browse button, Picup will launch. The user chooses from their photo roll or snaps a new photo. Next, Picup sends to photo to a service of your choice, imgur by default, to turn it into a URL. The URL is passed to a callback page in Mobile Safari and is opened as a new tab. A small bit of JavaScript on the callback page sends a message to your jQuery Mobile app. The message is the photo's URL and is submitted with your original form instead of photo data itself. The callback page then closes itself.
Server-side code should process either the photo data sent normally or the link to photo data sent by iOS devices.

Discussion
++++++++++++++++++++++++++++++++++++++++++++
This may sound like a complicated, roundabout way to upload a file but I have found it to be smoothest way to get the job done. To the user, it appears almost integrated.

First, let's take a look at the HTML in the form:

----
<div class="no-file-input">
  <p>To upload files on Mobile Safari, please be sure that you have Picup installed from the App Store.</p>
  <a href="http://itunes.apple.com/us/app/picup/id354101378?mt=8" data-role="button" rel="external">Install Picup</a>

  <a id="launchPicup" href="fileupload://new?callbackURL=" data-role="button" data-ajax="false">Browse</a>
  <input id="photoUrl" type="hidden" name="photoUrl" />
</div>

<label class="file-input">
  <span data-role="button">Browse</span>
  <input id="photoData" type="file" name="photoData" accept="image/*;capture=camera" style="visibility: hidden;" />
</label>
----

The div at the top is for iOS. Inside we have a note and a link to Picup in the App Store. Picup installs itself as a handler for the fileupload URL scheme. This means that any time a link points to fileupload://, the iOS device will launch Picup. Our link is created as a jQuery Mobile button. We also tell jQuery Mobile not to interfere with the link in any way by setting data-ajax to false.

To make the non-iOS side look similar, hide the actual file input and include a Browse button in your label. When a user taps the Browse button, it will launch the normal file browser for the device. As a bonus for Android 3+, the accept attribute will launch the camera app. Remove it if you don't want that behavior.

The JavaScript for this page has to decide which of these two sections to hide. We can do this by detecting whether or not the file input is disabled when jQuery Mobile creates the page. Also, we have to update the Picup link with an absolute URL to the callback page. jQuery Mobile includes a nice function to help with that. Assuming your page's id is "upload":

----
$("body").on( "pagecreate", "#upload", function( e ) {
  if ( $("#photoData").prop("disabled") ) {
    $(".file-input").hide();

    var callbackUrl = $.mobile.path.makeUrlAbsolute( "picup.html", window.location.href );

    $("#launchPicup").attr( "href", function( i, attr ) {
      return attr + callbackUrl;
    });
  } else {
    $(".no-file-input").hide();
  }
});
----

On an iOS device, the above code hides the regular file input. It then appends the absolute URL of our callback page, picup.html in this example, to the Picup link's href attribute. We append the URL because we want to retain the "fileupload://new?callbackURL=" already in the markup. On other devices, the snippet hides the iOS section.

After the user chooses a photo in Picup, the app returns them to Mobile Safari and opens a new tab to our callback URL. The callback page is almost entirely JavaScript and the user barely gets a chance to see it before it closes itself. The callback page must be on the same domain as your jQuery Mobile app.

----
var hash = window.location.hash.substring( 1 ),
    params = hash.split( "&" ),
    p;

for ( var i = 0; i < params.length; i++ ) {
  p = params[ i ].split( "=" );
  if ( p[ 0 ] === "remoteImageURL" ) {
    localStorage.setItem( "photoUrl", decodeURIComponent( p[ 1 ] ) );
    window.close();
    break;
  }
}
----

Picup sends the uploaded photo's URL via a remoteImageURL parameter in the callback page's hash. We search the hash and decode the URL when found. Your first thought might be to send the photo URL directly to the jQuery Mobile app using postMessage but a) we don't have a reference to that window and b) the only means to get one is window.open( url, name ) which might cause data or state loss in the original app because it refreshes the page. However, we can use the often ignored HTML5 storage event. Setting a value in localStorage on this tab will trigger an event in the jQuery Mobile app on the original tab. With that done, this tab closes itself and the following JavaScript in the jQuery Mobile app takes over:

----
$("window").on( "storage", function( e ) {
  if ( e.key === "photoUrl" && e.newValue ) {
    $("#photoUrl").val( e.newValue );
  }
});
----

In the event handler, e.newValue contains the photo URL we sent from our callback page. We set the hidden input's value to it and let the form post as usual.

There isn't a way to detect if Picup is installed but we can leave the photoUrl item in localStorage after a successful upload. If present during pagecreate and we want to clean up our UI a little, we can hide or remove the note and App Store link from our iOS section.

This could be done a lot nicer with one of HTML5's new file APIs, but there is no telling when or if Mobile Safari will get them. Until then, this is a functional work around.
