////

HTML5 localstorage

Author: Roberto Hernandez <rhernandez@overridethis.com>

Bio: Currently a Managing Consultant for Excella in the Washington, DC region. I have been designing and writing software solutions using Microsoft technology for the past 12 years. I am originally from the Dominican Republic and the proud father of two beautiful daughters that make my life special.

////

10.3 HTML5 localstorage
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Using HTML5 localstorage to store user information.

Solution
++++++++++++++++++++++++++++++++++++++++++++
The following code outlines a simple scheme that demos the of HTML5 LocalStorage API.

----
include::recipe-3-code/localstorage.html[]
----

Discussion
++++++++++++++++++++++++++++++++++++++++++++
The HTML5 LocalStorage API is very simple, it consists of two methods +setItem+ and +removeItem+ that allow you to either add or remove an item from the browsers LocalStorage. The following sample code shows a sample of adding and removing an item from the HTML5 LocalStorage.

[html,source]
====
// add item to HTML5 LocalStorage.
localStorage.setItem("jquery", "jquery");
// remove item from HTML5 LocalStorage
localStorage.removeItem("jquery");
====
One thing to note is not all browsers support HTML5 LocalStorage so your application should use this API cautiously. The sample code outlined uses the following code to detect HTML5 LocalStorage support.

[html,source]
====
function hasLocalStorageSupport() {
	try {
		var support = "support";
		localStorage.setItem(support, support);
		localStorage.removeItem(support);
		return true;
	} catch(e) {
		return false;
	}
}
====

[Warning]
====
Safe HTML5 feature detection is not trivial, you should leverage a well tested third party library to perform this task.  One such library is Modernizr - http://www.modernizr.com.
====






