////

Author: Anu Shahi <anu.shahi@gmail.com>

Notes:

* Code example should demonstrate form submission after successful validation (maybe display submitted values in alert).
* Add link to jQuery validation plugin
* Include minified versions of all scripts and css once example has been coded


////

#.# Form Validation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
+++++++++++++++++++++++++++++

Enabling client-side form validation for a typical jQuery Mobile application presents a range of challenges. Firstly, the single page application approach requires validation rules to be applied during initialization of a specific form page.  Secondly, due to the markup generated by jQuery Mobile during progressive enhancement, error messages must be placed appropriately around elements that fail validation, such as select lists and radio controls. This ensures errors blend in sensibly when viewed within enhanced forms.  Finally, event handlers must be registered to trigger 'as you type' validation for heavily enhanced form elements, where binding click handlers to the original native controls has no effect, such as select lists and radio controls.


Solution
+++++++++++++++++++++++++++++
Create a simple validation module that configures the jQuery validation framework to insert error labels sensibly around enhanced elements, together with binding additional event handlers to trigger validation of heavily enhanced elements.  The jQuery validation framework allows validation rules to be specified and easily bound to target form elements in both a declarative and programmatic way.  Validation is performed elegantly by triggering validation of form elements after an initial form submission, after which 'as you type' validation is enabled for each control.

The following snippet of code describes the general approach for discussion. In this case, validation will be enabled for 'myform', meaning the form will not be submitted until inputs 'firstElement' and 'anotherElement' contain non-empty values.

----
//enable validation for myform
var form = $( "#myform" );
formValidation.validate( form, {
  rules: {
    firstElement: "required",
    anotherElement: "required",
  }
});
----

Discussion
+++++++++++++++++++++++++++++

Let's start with a sample form page used to capture feedback on people's favourite snacks:

----
<div data-role="page" id="feedback">
  <div data-role="header">
    <h1>Feedback Form</h1>
  </div>
  <div data-role="content">
    <form action="/snackreview" method="POST">
      <div data-role="fieldcontain">
        <label for="region">Please enter your region:</label>
        <select name="region" id="region" data-native-menu="false">
          <option></option>
          <option>North</option>
          <option>South</option>
          <option>East</option>
          <option>West</option>
        </select>
      </div>
      <div data-role="fieldcontain">
        <fieldset data-role="controlgroup">
          <legend>
            Please select your favourite snack:
          </legend>
          <input type="radio" name="snack" id="cheetos">
          <label for="cheetos">Cheetos</label>
          <input type="radio" name="snack" id="doritos">
          <label for="doritos">Doritos</label>
          <input type="radio" name="snack" id="fritos">
          <label for="fritos">Fritos</label>
          <input type="radio" name="snack" id="sunchips">
          <label for="sunchips">Sun Chips</label>
        </fieldset>
      </div>
      <div data-role="fieldcontain">
        <label for="feedback">Please describe why you love your favourite snack:</label>
        <textarea name="feedback" id="feedback"></textarea>
      </div>
      <div data-role="fieldcontain">
        <button type="submit" data-theme="a">Send</button>
        <a href="#home" data-role="button">Cancel</a>
      </div>
    </form>
  </div>
</div>
----

The validation requirement for our sample form is that all fields are mandatory.  To enable such validation on our target page, we bind a function to the 'pageinit' event. This function selects the form and invokes the form validation module with the target form and a simple object containing form specific validation rules:

----
$( document ).on( "pageinit", "#feedback", function( event ) {
  var form = $( event.target ).find( "form" );
  formValidation.validate( form, {
    rules: {
      region: "required",
      snack: "required",
      feedback: "required"
    }
  });
});
----

Many types of validation are supported by the jQuery validation framework. Multiple rules may be combined for an element as follows:
----
rules: {
  measure: {
    required: true,
    digits: true,
    maxlength: 6
  }
}
----

TODO Describe validation module and styling....

