////

Author: Tyson Cadenhead <tcadenhead@appendto.com> 11/29/2012
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

2.4 How multipages works, how to use multipage pattern
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
There are some instances where we would like to include multiple pages in a single template.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Instead of making each link in our application go to a separate html page, we can actually embed multiple pages in a single template.

Discussion
++++++++++++++++++++++++++++++++++++++++++++
JQuery Mobile lets you embed as main pages in your template as you want. When you view your page, it will automatically display the first page in the template by default, but by using hashtag navigation, you can show and hide any of the pages in the DOM. Here is an example using the multipage pattern.

----
include::recipe-4-code/multipage.html[]
----

Since the data-role="page" attribute is set on all three pages, only our homepage will be displayed at first. When one of the homepage links are clicked, the homepage is hidden and the link that was clicked will be displayed. The data-title attribute can be used on pages and dialogs to change the title that is shown in the browser tab.