////

Author: Buddy James
Chapter Leader approved: <date>
Copy edited: 02/01/2013
Tech edited: <date>

////

2.10 Data-binding with Knockout.js
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
When developing HTML forms that take user input, you typically have to write JavaScript code to sync the data entered by the user with the underlying data model that will eventually be persisted to some sort of data storage.  If changes are made to your data model programmatically, you must check for these changes and reflect them on the client side input controls for the user to see.  This recipe will take introduce Knockout.js, a JavaScript library that enables the implementation of the Model-View-ViewModel UI pattern.  

Solution
++++++++++++++++++++++++++++++++++++++++++++
The recipe is made up of an HTML page that represents an ecommerce site with a shopping cart and an order summary.  The order form, shopping cart, and order summary displays are all data-bound to properties of a ViewModel object by way of Knockout.js.  This apporach allows you to cleanly separate the user input from the data persistence of the application by using the MVVM design pattern.  The MVVM design pattern is designed to separate your application into models that hold data, views that represent the user interface, and view models that present an abstraction between the models and views.  This separation of concerns will improve your code's architecture and increase testability.  You will write less code and achieve a more responsive UI than before thanks to Knockout.js.

----
include::recipe-10-code/example.html[]
----

Discussion
++++++++++++++++++++++++++++++++++++++++++++
As you can see, when JQuery starts, we will setup bindings on in our UI as data attributes that link back to properties of our ViewModel object.

The user interface:
The user interface is a simple html form that mimics a shopping cart with an order summary.  The html form has input elements to allow the user to enter their billing information.  The first thing to note is the data-bind attributes of each input element.  KnockoutJS uses the html 5 data- attributes to define the binding behavior elements in your page.

The Customer's information entry:
Each field here is also databound to the display only fields in the Order Review section.  If you change any of the user's details, they are automatically refreshed in the review section.

The item quantity text box allows you to change the quanity of the items to be order and as a result the Knockout.js bindings will perform a calculation on the quantity and price and the result is automatically reflected in the order summary.  This would be code that you would have to write yourself without knockout.js.

The product order section
<TODO>

The order review section
<TODO>

The ViewModel
<TODO>
