////

jQueryMobile supports three types of toolbars.
1.Header bars which is displayed as the top most item before page content.
Normally used to show page title and buttons/icons.
2.Footer bars which is displayed as the bottom most item after page content.
Normally contains buttons/icons.
3.Navbars which can be displayed within header/footer bars or with in page content to show seperate level of buttons/icons/other controls. 

Author: John Chacko <poonkave@gmail.com>

////

#.# Embedding controls in toolbars
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Sometimes we want to embed controls in the header or footer toolbars on the page. One common reason is to let the user toggle the current language of the page.

In order to this, we need to be able to place a control into the header and position it properly to the right or left side.

Solution
++++++++++++++++++++++++++++++++++++++++++++

[source, html]
---- 
<!DOCTYPE html>
<html>
  <head>
    <title>Embedding controls in toolbar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css"/>
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
	<style>
		#home-header .ui-select { 
			float: right
		}
	</style>
  </head>
  <body>
    <div id="home" data-role="page" data-theme="b">
		<div id="home-header" data-role="header" data-position="inline">
			<select name="language" id="language" data-native-menu="false" data-theme="b">
				<option value="English">English</option>
				<option value="French">French</option>
				<option value="Russian">Russian</option>
				<option value="Polish">Polish</option>
			</select>
			<h1>Home Page</h1> 

		</div>
		<div data-role="content"></div> 
    </div>
  </body>
</html>
 
Discussion
++++++++++++++++++++++++++++++++++++++++++++
In order to fit the control the right of the header, we've set it to float right. 
