////

This is a comment block.  Put notes about your recipe here and also your author information.

Author: Max Lynch <maxlynch@uwalumni.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

2.4 Fixing Toolbars
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
We want to display a header or footer toolbar at all times, and float it above the content of the page.

Solution
++++++++++++++++++++++++++++++++++++++++++++
jQuery Mobile provides fixed positioning support for toolbars. In fact, it's a simple matter of adding data-position="fixed" to the toolbar as shown below:

[source, html]
-----
<!DOCTYPE html> 
<html> 
	<head> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
</head> 
<body>
  <div data-role="page">
		<div data-role="header" data-position="fixed">
			<h3>Header</h3>
		</div>
		<div data-role="content">
			<div style="height: 1000px">
				A really tall div
			</div>
		</div>
		<div data-role="footer" data-position="fixed">
			<h3>Footer</h3>
		</div>
	</div>
</body>
</html>
-----
 
Discussion
++++++++++++++++++++++++++++++++++++++++++++
In this recipe we've set the data-position attribute to "fixed" to keep the header and footer toolbars fixed at the top and bottom of the viewport, respectfully.

This keeps the center content padded enough to show the toolbars while allowing the toolbars to stay fixed in pace as the center content scrolls. We've added
a really tall div to demonstrate the effect.