////

Recipe(s) for Dialogs

Author: Anne-Gaelle Colom <coloma@wmin.ac.uk>

TODO: LOTS!!!
////

#.# Recipe Title
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
You want to display a small page to the user in a way that will not look like or behave like a standard page. Instead, you want this to be more like a dialog box.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Create the page as a standard jQuery Mobile page, and add the data-rel="dialog" attribute to the link to that page: 

[source,html]
TODO: CODE HERE

Discussion
++++++++++++++++++++++++++++++++++++++++++++
Anne's picture here is a link to the page with the id contact_anne. contact_anne is the id of a standard jQueryMobile page which is in the same file as the picture on which we clicked, which allows us to call the page by simply linking to its id (see chapter xxx for more information on linking pages).

By adding the data-rel="dialog" as an attribute to the link to the contact_anne page id, the page will not be displayed in full screen like all standard pages. Instead, it will come as a dialog box floating in the middle of the screen. 

It is possible to add a data-transition option that will define the transition used to bring the dialog box. By default, the reverse set transition is used to leave the page.


