////

This is a comment block.  Put notes about your recipe here and also your author information.

Author: Max Lynch <maxlynch@uwalumni.com>

////

#.# Persistent Footer Navbar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
We want to position a NavBar at the bottom of our app and keep it at the bottom regardless of page transitions and navigation.

Solution
++++++++++++++++++++++++++++++++++++++++++++
In this example, we combine the fixed positioning support for toolbars with a Nav Bar embedded in the footer toolbar. This gives us the desired
effect of a Nav Bar fixed to the bottom of the app that stays there regardless of the content of the page.

We also duplicate this toolbar across several pages, giving us the effect of a Nav Bar which stays at the bottom despite navigation and changing
page content.

[source, html]
----
<!DOCTYPE html> 
<html> 
	<head> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
</head> 
<body>
  <div data-role="page" id="page1">
		<div data-role="content">
			Page 1
		</div>
		<div data-role="footer" data-id="fixedbar" data-position="fixed">
			<div data-role="navbar">
				<ul>
					<li><a href="page1.html" class="ui-btn-active ui-state-persist">Page 1</a></li>
					<li><a href="page2.html">Page 2</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>
----

[source, html]
----
	<div data-role="page" id="page2">
		<div data-role="content">
			Page 2
		</div>
		<div data-role="footer" data-id="fixedbar" data-position="fixed">
			<div data-role="navbar">
				<ul>
					<li><a href="page1.html">Page 1</a></li>
					<li><a href="page2.html" class="ui-btn-active ui-state-persist">Page 2</a></li>
				</ul>
			</div>
		</div>
	</div>
----
 
Discussion
++++++++++++++++++++++++++++++++++++++++++++
In this recipe we've added a page footer to each page we want the toolbar to reside on. We've also set the toolbars position to "fixed". In order to provide the effect of the toolbar 
persisting across page navigations, we set the data-id of the toolbar to the same value on each page. Also, to indicate the current page on the Nav Bar, we added
the class="ui-btn-active ui-state-persist" to each active button for the page. 