////

jQueryMobile supports three types of toolbars.
1.Header bars which is displayed as the top most item before page content.
Normally used to show page title and buttons/icons.
2.Footer bars which is displayed as the bottom most item after page content.
Normally contains buttons/icons.
3.Navbars which can be displayed within header/footer bars or with in page content to show seperate level of buttons/icons/other controls. 

Author: John Chacko <poonkave@gmail.com>

////

#.# Embedding controls in toolbars
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Needs to provide an option for user to change website language.

Solution
++++++++++++++++++++++++++++++++++++++++++++
[source, html]
---- 
<!DOCTYPE html>
<html>
  <head>
    <title>Embedding controls in toolbar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css"/>
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
  </head>
  <body>
    <div id="home" data-role="page" data-theme="b">
  	  <div data-role="header" data-position="inline">
		    <h1>Home Page</h1> 
		    <div data-role="navbar" data-theme="a" class="ui-bar"> 
		      <div class="ui-grid-b">
		        <div class="ui-block-a"></div>
		        <div class="ui-block-b"></div>
            <div class="ui-block-c">
						  <select name="select-choice-1" id="select1" data-native-menu="false" data-theme="b">
								  <option value="English">English</option>
									<option value="French">French</option>
									<option value="Russian">Russian</option>
									<option value="Polish">Polish</option>
						  </select>
		        </div>
		      </div>
		    </div>
      </div>
      <div data-role="content"></div> 
    </div>
  </body>
</html>
 
Discussion
++++++++++++++++++++++++++++++++++++++++++++
A custom select menu is embeded inside a navbar after header.
Grid layout is used to align selectbox to the right.

