////

Improving readability on desktop and mobile devices.

Author: Ray Daly <raydaly@gmail.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

#.# How to make pages readable on desktops and other wide screens
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Your app looks fine on the phone but not on your desktop monitor. Text lines are too long to read comfortably.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Limit the maximum width of the page to a comfortable number, and center the content.

[source, css]
---- 
.jqpage { max-width: 790px; margin-left: auto; margin-right: auto;}
----

and give each div with a data-role of page a class of jqpage:

[source, html]
---- 
<div id="load" data-role="page" class="jqpage">
----

Discussion
++++++++++++++++++++++++++++++++++++++++++++
It is very easy when working with jQuery Mobile to concentrate on how your app looks on a small screen. However, some people will use their desktop browser to view your jQuery Mobile website.

A simple solution to this problem is to use CSS to set the max-width of your app to 790px. Then, using a left and right margin of auto, the app will center in the desktop browser regardless of the width.

This avoids the problem of lines of text that are too long for comfortable reading. This is a simple way to improve the cross-device 'readability' of your app.


