////

Author: Tyson Cadenhead <tcadenhead@appendto.com> 11/28/2012
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

2.5 Fullscreen Toolbar Positioning
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
We want to be able to display a toolbar that will expand to match the width of the screen and persist as we navigate the page.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Using the data-position="fixed" property on our headers and footers, we can make them float at the top and bottom of the screen as we navigate.

Discussion
++++++++++++++++++++++++++++++++++++++++++++
By adding data-position="fixed" to our toolbars, they will always persist on the screen. A fixed-position setup would typically look like this:

----
include::recipe-5-code/example.html[]
----

To make the toolbar truly full-screen, change data-fullscreen="false" to data-fullscreen="true" on the header toolbar. That will allow the user to scroll all the way to the top and bottom of the screen. One issue that will create is that part of the content will be partially obscured by our toolbars. Because of that, full-screen toolbars should only be used for content that doesn't have to be completely visible. A good example would be a photo application. Since it isn't essential for the user to see the top and bottom parts of photos, this sort of interface would be suitable.