////

Recipe for collapsible sets

Author: Anne-Gaelle Colom <coloma@westminster.ac.uk>
TO DO: Complete solution and add full code and screen shots
////

#.# Collapsible sets
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
You want to use more than one collapsible, but when one collapsible is expanded, you want the others to be collapsed.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Use a collapsible set by having your collapsibles inside an additional div container with data-role="collapsible-set": 

[source,html]
<div data-role="collapsible-set">
	<div data-role="collapsible" data-theme="a" data-content-theme="c" >
	<h3>Virtual Noticeboard</h3>
		<dl>
			<dt>News: </dt>
			<dd>I am currently working on my recipes for the jQuery Mobile Cookbook...</dd>
			<br />
			<dd>I will be attending the next jQuery UK Conference and will provide highlights on my blog.</dd>
			<br/>
			<dt>General Information: </dt>
			<dd>All students are invited to attend the module fair on Wednesday.</dd>
			<br />
			<dd>All level 5 students are invited to the Final Year Project talk in the Large Lecture Theatre on Tuesday 1pm-2pm</dd>
		</dl>
	</div>
	<div data-role="collapsible" data-theme="a" data-content-theme="c">
		<h3>Area of expertise</h3>
		<ul>
			<li>jQuery Mobile</li>
			<li>JavaScript</li>
			<li>Front-end Web development</li>
			<li>User Experience</li>
		</ul>
	</div>
	<div data-role="collapsible" data-theme="a" data-content-theme="c">
		<h3>Teaching</h3>
		<p>Teaching details here...</p>
	</div>
	<div data-role="collapsible" data-theme="a" data-content-theme="c">
		<h3>Projects</h3>
		<p>Projects details here...</p>
	</div>
</div>


Discussion
++++++++++++++++++++++++++++++++++++++++++++
A collapsible set is a set of collapsibles that work together. All collapsibles in a set may be collapsed at the same time, and only one collapsible in a set can be expanded at any one time. The collapsibles in the set will look like a block of collapsibles, with the top and bottom rounded corners applied to the extremities of the set by default. 

Just as you are able to add theme to the header or the content of the collapsible, you can do the same with the collapsible set, by adding data-theme to the collapsible header, and/or to the collapsible content.
