////

This is a comment block.  Put notes about your recipe here and also your author information.

Author: Don Walter <donmwalter@gmail.com>
Bio: Don is an Application and Web Developer living in Villa Hills, KY with his wife and son. You can follow him on Twitter: @donwalter

////

5.2 Common Formatting of Lists
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
// Describe your problem here, in one or two sentences.  At a maximum, keep it to a single paragraph.

You may want to alter the appearance and styling of your list, or display some additional helpful information.


Solution
++++++++++++++++++++++++++++++++++++++++++++
// Describe the solution to your recipe here.  It should be one to two paragraphs long.  It may include a code sample.
// 1. Data Inset True/False
// 2. List Dividers
// 3. Adding Images
// 4. Changing Icons
// 5. Split Button Lists
// 6. Count Bubbles

You can apply a variety of formatting to your lists, to both increase readability, and add more information. You can apply an inset to your list, which will give the list left and right margins, as well as rounded corners. In cases where you might want to have more than one action per list item, you can create a split button list. You can add thumbnails or icons, add count bubbles to show the number of results for a particular list item, and add dividers to your list to help separate information. There are many options to customize your list to suit the data you would like to display.


Discussion
++++++++++++++++++++++++++++++++++++++++++++
// The discussion of your recipe should be where you break down a description of the problem you are solving.  It is the primary discussion place and should be where code examples are put.  It could be 4-6 paragraphs long.

=== Data Inset True/False
An inset list, is just a standard list that sits inside the content area with a margin all the way around, as opposed to the list elements going all the way across the screen. It also adds rounded corners to the list, to help it stylistically fit in better with the other inset elements on the page. To make an inset list, all you need to do is add the `data-inset="true"` attribute to the list (`ul` or `ol`)

[source, html]
----
<ul data-role="listview" data-inset="true">
  <li>Ben Folds Five</li>
  <li>Cake</li>
  <li>Guster</li>
</ul>
----

=== List Dividers
// Text here

[source, html]
----
// Code here
----

=== Adding Images
// Text here

[source, html]
----
// Code here
----

=== Changing Icons
// Text here

[source, html]
----
// Code here
----

=== Split Button Lists
Sometimes, you need a list element to have multiple actions assigned to it... maybe you would like to give your users the ability to view an items details, or purchase that item, both from the same list element. This can be done with a Split Button List. To do this, you just need to add a second link inside the `li`, and jQuery Mobile does the rest! You can take this a step further and customize the right split icon, if you'd like. To do this, you just need to add a `data-split-icon` attribute with whatever icon name you'd like to use. You can also theme the split button swatch color with a `data-split-theme` attribute

[source, html]
----
<ul data-role="listview" data-split-icon="star" data-split-theme="c">
  <li>
    <a href="details.html">
    <h3>Ben Folds Five</h3>
    <p>Ben Folds Five</p>
    </a>
    <a href="purchase.html">Purchase album</a>
  </li>
  <li>
    <a href="details.html">
    <h3>Whatever And Ever Amen</h3>
    <p>Ben Folds Five</p>
    </a>
    <a href="purchase.html" data-rel="dialog" data-transition="slideup">Purchase album</a>
  </li>
  <li>
    <a href="details.html">
    <h3>Naked Baby Photos</h3>
    <p>Ben Folds Five</p>
    </a>
    <a href="purchase.html" data-rel="dialog" data-transition="slideup">Purchase album</a>
  </li>
</ul>
----

=== Count Bubbles
// Text here

[source, html]
----
// Code here
----