////

This is a comment block.  Put notes about your recipe here and also your author information.

Author: Kevin Old <kevin@kevinold.com>
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

5.9 Various Ways to Theme a List 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
You would like to theme your jQuery Mobile site with complimenting colors for your brand.  You may also wish to include icons or images to help users with identification.

Solution
++++++++++++++++++++++++++++++++++++++++++++
jQuery Mobile provides 6 default themes and an architecture which allows you to customize most elements of a list.

Discussion
++++++++++++++++++++++++++++++++++++++++++++
To add a theme to an element in jQuery Mobile, the "data-theme" attribute is used.  Themes are named A-E, the default being C.

A basic list with Theme C applied.

[source, html]
----
<ul data-role="listview" id="characters" data-theme="c">
  <li>Elmo</li>
  <li>Big Bird</li>
  <li>Ernie</li>
  <li>Bert</li>
</ul>
----

Here we incorporate an inset list, multiple themes for the list styling for the list itself, divider and count bubbles.

[source, html]
----
<ul data-role="listview" data-inset="true" data-theme="d" data-divider-theme="b" data-count-theme="e">
  <li data-role="list-divider">Gmail</li>
  <li>Inbox<span class="ui-li-count">15</span></li>
  <li>Sent<span class="ui-li-count">7</span></li>
  <li>Important<span class="ui-li-count">50</span></li>
</ul>
----

Note: The jQuery Mobile ThemeRoller (http://jquerymobile.com/themeroller/) is an excellent tool in building a custom theme for jQuery Mobile.
