////

Author: Kevin Old <kevin@kevinold.com>
Bio: 
>>> TODO: Insert some information above about yourself in the Bio:
Chapter Leader approved: <date>
Copy edited: <date>
Tech edited: <date>

////

5.9 Various Ways to Theme a List
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++

You want to apply a theme to a list and you want to include icons or images to help users with identification.
>>> TODO: "complimenting" should be "complementing" or "complementary"

Solution
++++++++++++++++++++++++++++++++++++++++++++

jQuery Mobile provides six default themes and an architecture that allows you to customize most elements of a list.

Discussion
++++++++++++++++++++++++++++++++++++++++++++

To add a theme to an element in jQuery Mobile, use the "data-theme" attribute. Themes are named A-E, the default being C.

A basic list with Theme C applied.
>>> TODO: You might say, "The following is a basic..." to attach this statement with the markup following. Be careful not to say "above" or "below" because these snippets could be on the next page.

[source, html]
----
<ul data-role="listview" id="characters" data-theme="c">
  <li>Elmo</li>
  <li>Big Bird</li>
  <li>Ernie</li>
  <li>Bert</li>
</ul>
----

Here we incorporate an inset list, multiple themes for the list styling for the list itself, divider and count bubbles.
>>> TODO: Same idea as mentioned in the previous TODO. "In the next snippet of markup we are incorporating an..."
>>> NOTE: I think it is fine combining some of the element as you've done. Two or three is probably okay, but any more might be hard for the reader to comprehend all of the changes. I think at the very end it might be okay to combine a whole lot of things you showed throughout the recipe to reveal the power of a themed list. A before & after shot might even be impressive side-by-side?

[source, html]
----
<ul data-role="listview" data-inset="true" data-theme="d" data-divider-theme="b" data-count-theme="e">
  <li data-role="list-divider">Gmail</li>
  <li>Inbox<span class="ui-li-count">15</span></li>
  <li>Sent<span class="ui-li-count">7</span></li>
  <li>Important<span class="ui-li-count">50</span></li>
</ul>
----

Note: The jQuery Mobile ThemeRoller (http://jquerymobile.com/themeroller/) is an excellent tool in building a custom theme for jQuery Mobile.
