////

This recipe shows how to use a normal list as well an an inset list to layout form elements.

Author: Daniel Mohl <danmohl@gmail.com>

Bio: Daniel Mohl is a Microsoft MVP and F# Insider. He blogs at blog.danielmohl.com and you can follow him on Twitter at twitter.com/dmohl.

////

5.6 How to Use a List to Layout Form Data
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Lists are very powerful and you will find that many scenarios that would have been done in multiple ways on a website, will often end up translating to lists when building a mobile application with jQuery Mobile.
One scenario that you may be faced with is how to create a quick form that automatically takes on the look and feel of the lists that reside in other aspects of your applications.

Solution
++++++++++++++++++++++++++++++++++++++++++++
Add some content here regarding the solution...

[source, html]
----
<div data-role="page" id="surveyPage">

	<div data-role="content">
		<form action="#surveyCompletePage" method="get" data-ajax="false">
			<ul data-role="listview" data-theme="d" > 
				<li data-role="fieldcontain">
					<label>Your Name:</label>
					<input type="text" name="yourName" id="yourName" value="" />
				</li>
				<li data-role="fieldcontain">
					 <label>Favorite Language:</label>
					 <fieldset data-role="controlgroup">
						<input type="radio" name="favoriteLanguage" id="javaScript" value="javaScript"/>
						<label for="javaScript">JavaScript</label>

						<input type="radio" name="favoriteLanguage" id="ruby" value="ruby" />
						<label for="ruby">Ruby</label>

						<input type="radio" name="favoriteLanguage" id="fsharp" value="fsharp" />
						<label for="fsharp">F#</label>

						<input type="radio" name="favoriteLanguage" id="coffeeScript" value="coffeeScript" />
						<label for="coffeeScript">CoffeeScript</label>

						<input type="radio" name="favoriteLanguage" id="java" value="java" />
						<label for="java">Java</label>

						<input type="radio" name="favoriteLanguage" id="csharp" value="csharp" />
						<label for="csharp">C#</label>
					</fieldset>
				</li>
				<li data-role="fieldcontain">
					<label>Do you use this language to develop for the:</label>
					<fieldset data-role="controlgroup" data-type="horizontal">
						<input type="radio" name="languageUse" id="usedForClientSide" value="usedForClientSide"/>
						<label for="usedForClientSide">Client</label>

						<input type="radio" name="languageUse" id="usedForServerSide" value="usedForServerSide" />
						<label for="usedForServerSide">Server</label>

						<input type="radio" name="languageUse" id="usedForBoth" value="usedForBoth" />
						<label for="usedForBoth">Both</label>
					</fieldset>	
				</li>
				<li data-role="fieldcontain">	
					<label>How many hours per week do you write server-side code?</label>
					<div data-role="fieldcontain">							
						<input type="range" name="serverSideCodingHours" id="serverSideCodingHours" value="0" min="0" max="100" />
					</div>
				</li>
				<li>
					<fieldset class="ui-grid-a">
						<div class="ui-block-a"><a href="#" data-role="button" data-theme="d">Cancel</a></div>
						<div class="ui-block-b"><button type="submit" data-theme="b">Save</button></div>
					</fieldset>
				</li>
			</ul>
		</form>
	</div>

</div>

<div data-role="page" id="surveyCompletePage">

	<div data-role="content">
	Thanks for completing this survey
	</div>
	
</div>
----

Discussion
++++++++++++++++++++++++++++++++++++++++++++
The discussion of your recipe should be where you break down a description of the problem you are solving.  It is the primary discussion place and should be where code examples are put.  It could be 4-6 paragraphs long.

Bonus
++++++++++++++++++++++++++++++++++++++++++++
This will provide a quick, more advanced approach for dynamically displaying form elements based on input in other form elements.

Something like this...

[source, html]
----

<!-- Non-relevant code ommitted -->

<li data-role="fieldcontain">
	 <label>Favorite Language:</label>
	 <fieldset data-role="controlgroup">
		<input type="radio" name="favoriteLanguage" id="javaScript" value="javaScript" data-dependency-class="clientAndServerSide"/>
		<label for="javaScript">JavaScript</label>

		<input type="radio" name="favoriteLanguage" id="ruby" value="ruby" data-dependency-class="serverSide" />
		<label for="ruby">Ruby</label>

		<input type="radio" name="favoriteLanguage" id="fsharp" value="fsharp" data-dependency-class="clientAndServerSide" />
		<label for="fsharp">F#</label>

		<input type="radio" name="favoriteLanguage" id="coffeeScript" value="coffeeScript" data-dependency-class="clientAndServerSide" />
		<label for="coffeeScript">CoffeeScript</label>

		<input type="radio" name="favoriteLanguage" id="java" value="java" data-dependency-class="serverSide" />
		<label for="java">Java</label>

		<input type="radio" name="favoriteLanguage" id="csharp" value="csharp" data-dependency-class="clientAndServerSide" />
		<label for="csharp">C#</label>
	</fieldset>
</li>
<li data-role="fieldcontain" class="toggleElement clientAndServerSide">
	<label>Do you use this language for development on the:</label>
	<fieldset data-role="controlgroup" data-type="horizontal">
		<input type="radio" name="languageUse" id="usedForClientSide" value="usedForClientSide"/>
		<label for="usedForClientSide">Client</label>

		<input type="radio" name="languageUse" id="usedForServerSide" value="usedForServerSide" />
		<label for="usedForServerSide">Server</label>

		<input type="radio" name="languageUse" id="usedForBoth" value="usedForBoth" />
		<label for="usedForBoth">Both</label>
	</fieldset>	
</li>
<li data-role="fieldcontain" class="toggleElement serverSide">	
	<label>How many hours per week do you write server-side code?</label>
	<div data-role="fieldcontain">
		<input type="range" name="serverSideCodingHours" id="serverSideCodingHours" value="0" min="0" max="100" />
	</div>
</li>

<!-- Non-relevant code ommitted -->
----

And add a little bit of JavaScript...

[source, javascript]     
----
$( document ).delegate( "#surveyPage", "pagebeforeshow", function( event ) {
	// Hide all dependency questions
	$( ".toggleElement" ).hide();
	
	// Ensure that no radio buttons are initially selected
	$( "input[type=radio]" ).attr( "checked", false ).next( "label" ).removeClass( "ui-btn-active" );
	
	// Bind an event handler to the change JavaScript event to toggle the visibility of the dependency questions
	$( "input[name=favoriteLanguage]:radio" ).change(function() {
		var $classToShow;
		// Hide all dependency questions
		$( ".toggleElement" ).hide();
		// Get the value of the data-dependency-class attribute 
		$classToShow = $( this ).data( "dependencyClass" );
		// Show the appropriate dependency question
		$( "." + $classToShow ).show();
	});		
});
----