////

This recipe shows how to use a normal list as well an an inset list to layout form elements.

Author: Daniel Mohl <danmohl@gmail.com>

Bio: Daniel Mohl is a Microsoft MVP and F# Insider. He blogs at blog.danielmohl.com and you can follow him on Twitter at twitter.com/dmohl.

////

5.6 How to Use a List to Layout Form Data
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
++++++++++++++++++++++++++++++++++++++++++++
Lists are very powerful and you will find that many scenarios that would have been done in various ways on a website, will often end up translating to lists when building a mobile application with jQuery Mobile. One scenario that you may be faced with is how to quickly create a form that automatically takes on the look and feel of the lists that reside in other areas of your applications. How can this be achieved with jQuery Mobile?

Solution
++++++++++++++++++++++++++++++++++++++++++++
The solution is quite simple. All that you need to do is wrap your list in a form element and add input elements as children of the desired list item element. A complete example with a few different input element types is shown below:
[source, html]
----
<div data-role="page" id="surveyPage">

	<div data-role="content">
		<form action="#surveyCompletePage" method="get" data-ajax="false">
			<ul data-role="listview" data-theme="d" > 
				<li data-role="fieldcontain">
					<label>Your Name:</label>
					<input type="text" name="yourName" id="yourName" value="" />
				</li>
				<li data-role="fieldcontain">
					 <label>Favorite Language:</label>
					 <fieldset data-role="controlgroup">
						<input type="radio" name="favoriteLanguage" id="javaScript" value="javaScript"/>
						<label for="javaScript">JavaScript</label>

						<input type="radio" name="favoriteLanguage" id="ruby" value="ruby" />
						<label for="ruby">Ruby</label>

						<input type="radio" name="favoriteLanguage" id="fsharp" value="fsharp" />
						<label for="fsharp">F#</label>

						<input type="radio" name="favoriteLanguage" id="coffeeScript" value="coffeeScript" />
						<label for="coffeeScript">CoffeeScript</label>

						<input type="radio" name="favoriteLanguage" id="java" value="java" />
						<label for="java">Java</label>

						<input type="radio" name="favoriteLanguage" id="csharp" value="csharp" />
						<label for="csharp">C#</label>
					</fieldset>
				</li>
				<li data-role="fieldcontain">
					<label>Do you use this language to develop for the:</label>
					<fieldset data-role="controlgroup" data-type="horizontal">
						<input type="radio" name="languageUse" id="usedForClientSide" value="usedForClientSide"/>
						<label for="usedForClientSide">Client</label>

						<input type="radio" name="languageUse" id="usedForServerSide" value="usedForServerSide" />
						<label for="usedForServerSide">Server</label>

						<input type="radio" name="languageUse" id="usedForBoth" value="usedForBoth" />
						<label for="usedForBoth">Both</label>
					</fieldset>	
				</li>
				<li data-role="fieldcontain">	
					<label>How many hours per week do you write server-side code?</label>
					<div data-role="fieldcontain">							
						<input type="range" name="serverSideCodingHours" id="serverSideCodingHours" value="0" min="0" max="100" />
					</div>
				</li>
				<li>
					<fieldset class="ui-grid-a">
						<div class="ui-block-a"><a href="#" data-role="button" data-theme="d">Cancel</a></div>
						<div class="ui-block-b"><button type="submit" data-theme="b">Save</button></div>
					</fieldset>
				</li>
			</ul>
		</form>
	</div>

</div>

<div data-role="page" id="surveyCompletePage">

	<div data-role="content">
	Thanks for completing this survey
	</div>
	
</div>
----


Discussion
++++++++++++++++++++++++++++++++++++++++++++
This solution allows you to quickly setup forms that render just like other lists without any custom client-side code. The attributes of the form element work exactly like they would outside of a list. 
[NOTE]
Forms are described in detail in chapter 7. 

This provides a nice blend of jQuery Mobile forms and lists functionality. Convenently, the things that you have already learned about lists and that you will learn about forms in recipes found later in this book, apply in exactly the same way. For example, to make the list shown above into an inset list, simply change the unorder list element to look like this:
[source, html]
----
<ul data-role="listview" data-theme="d" data-inset="true"> 
----
The output of this change is shown below:
<-- Need to add a screenshot -->

Bonus
++++++++++++++++++++++++++++++++++++++++++++
As a bonus, you may run into scenarios where the list needs to dynamically display different form elements depending on input to other elements. There are several ways to accomplish this type of functionality and you will learn about many of these way throughout the rest of the book. One option for accomplishing this is to slightly modify the list elements and then add a little bit of JavaScript. The following example quickly illustrates this.

[source, html]
----
<!-- Non-relevant code ommitted -->

<li data-role="fieldcontain">
	 <label>Favorite Language:</label>
	 <fieldset data-role="controlgroup">
		<input type="radio" name="favoriteLanguage" id="javaScript" value="javaScript" data-dependency-class="clientAndServerSide"/>
		<label for="javaScript">JavaScript</label>

		<input type="radio" name="favoriteLanguage" id="ruby" value="ruby" data-dependency-class="serverSide" />
		<label for="ruby">Ruby</label>

		<input type="radio" name="favoriteLanguage" id="fsharp" value="fsharp" data-dependency-class="clientAndServerSide" />
		<label for="fsharp">F#</label>

		<input type="radio" name="favoriteLanguage" id="coffeeScript" value="coffeeScript" data-dependency-class="clientAndServerSide" />
		<label for="coffeeScript">CoffeeScript</label>

		<input type="radio" name="favoriteLanguage" id="java" value="java" data-dependency-class="serverSide" />
		<label for="java">Java</label>

		<input type="radio" name="favoriteLanguage" id="csharp" value="csharp" data-dependency-class="clientAndServerSide" />
		<label for="csharp">C#</label>
	</fieldset>
</li>
<li data-role="fieldcontain" class="toggleElement clientAndServerSide">
	<label>Do you use this language for development on the:</label>
	<fieldset data-role="controlgroup" data-type="horizontal">
		<input type="radio" name="languageUse" id="usedForClientSide" value="usedForClientSide"/>
		<label for="usedForClientSide">Client</label>

		<input type="radio" name="languageUse" id="usedForServerSide" value="usedForServerSide" />
		<label for="usedForServerSide">Server</label>

		<input type="radio" name="languageUse" id="usedForBoth" value="usedForBoth" />
		<label for="usedForBoth">Both</label>
	</fieldset>	
</li>
<li data-role="fieldcontain" class="toggleElement serverSide">	
	<label>How many hours per week do you write server-side code?</label>
	<div data-role="fieldcontain">
		<input type="range" name="serverSideCodingHours" id="serverSideCodingHours" value="0" min="0" max="100" />
	</div>
</li>

<!-- Non-relevant code ommitted -->
----

And add a little bit of JavaScript...

[source, javascript]     
----
$( document ).delegate( "#surveyPage", "pagebeforeshow", function( event ) {
	// Hide all dependency questions
	$( ".toggleElement" ).hide();
	
	// Ensure that no radio buttons are initially selected
	$( "input[type=radio]" ).attr( "checked", false ).next( "label" ).removeClass( "ui-btn-active" );
	
	// Bind an event handler to the change JavaScript event to toggle the visibility of the dependency questions
	$( "input[name=favoriteLanguage]:radio" ).change(function() {
		var $classToShow;
		// Hide all dependency questions
		$( ".toggleElement" ).hide();
		// Get the value of the data-dependency-class attribute 
		$classToShow = $( this ).data( "dependencyClass" );
		// Show the appropriate dependency question
		$( "." + $classToShow ).show();
	});		
});
----