////

Author: Cory Gackenheimer <cory.gack@gmail.com

////


8.13 Debugging Your IOS App
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Problem
+++++++
You have created a remarkable jQuery Mobile application. You have debugged and tested successfully on a desktop browser, but now you must debug on your iOS device which can be more difficult and less intuitive than debugging in a desktop browser.

Solution
++++++++
Fortunately for you as a developer, the mobile remote debugging sector of developer tooling is growing more robust each day. There several options available to a developer, where you can append a debug script to your jQuery Mobile application, access a remote server that will relay information from and to your mobile device. Some of these projects are wholly web-based, while others may require some local server installation in order to work properly.

Discussion
++++++++++
The first solution for remote device debugging utilizes a service at jsconsole.com. This is a web-based command line utility which can set a listener and bridge the gap between device and the jsconsole's simulated console.  There are two steps to bridge this gap.  First one must type ":listen" in the jsconsole.com window. The ":listen" command can be followed by an optional identifier of the users choosing, but if one is not provided an identifier will be generated.  The second step to utilizing jsconsole.com for remote debugging is to add a script to your HTML file that includes the remote.js file of the jsconsole project and points to the identifier you either specified or were given in the first step.

----
<script src="http://jsconsole.com/remote.js?IDENTIFIER"></script>
----

Once this script is in place on your app, jsconsole will allow you to remotely control your app, intercept errors as if you were debugging within the console on your device.

Weinre, or WebKit Inspector Remote, is a server that will also bridge the gap between your target device and a desktop debugging client. This can be installed locally, or you can utilize many of the readily available Weinre services available to web developers. One example of these remote debugging services can be found at http://debug.phonegap.com where you will not need to run the server locally at all. This setup is similar to jsconsole where you will name a secret identifier that you will attach to the script you insert into your. So if you utilize your same IDENTIFIER you will need to add the following script to your cordova project:

----
<script src="http://debug.phonegap.com/target/target-script-min.js#IDENTIFIER"></script>
----

Then you'll need to point your browser to the following debug client, 'http://debug.phonegap.com/client/#IDENTIFIER'. Since the Weinre project is based on the WebKit inspector, it works best on a WebKit based browser.

Another popular remote inspection tool is Edge Inspect from Adobe. Edge Inspect is another tool that extends the functionality of the Weinre service. To get started with Edge inpect you'll need a couple things. One you will need to have the free mobile application installed on your device. You will also need the Edge Inspect extension for the Google Chrome browser installed on your desktop or laptop. The third piece required is the Edge Inspect application you will install and run on your Mac or PC. These three components together will help you to run the service to identify and synchronize your mobile devices to your desktop browser, provided they are running on the same wifi network. Edge Inspect allows you to browse the sites you wish to debug on Chrome and all of your devices will shadow that browsing. Along with the Chrome inspector, if you toggle inspection on the Edge Inspect browser extension panel, you will get Weinre version of the inspector tools for use inspecting your remote devices.

The mobile remote debugging space is growing fast and there are certain to be many more innovations that help bridge the gap between the comfort of desktop debugging and the need to debug on a mobile device. The solutions listed in this recipe is only a small sampling of what is available and of what may come in the future of remote debugging.